FROM  arm64v8/ubuntu:20.04
LABEL org.opencontainers.image.source = &quot;https://github.com/NotTimIsReal/ptero-images&quot;
RUN adduser -D -h /home/docker docker
USER docker
ENV         USER=container HOME=/home/container
WORKDIR     /home/container
RUN apt -y update
RUN apt -y install git curl nodejs python3 sudo