FROM  arm64v8/ubuntu:18.04
LABEL org.opencontainers.image.source = &quot;https://github.com/NotTimIsReal/ptero-images&quot;
RUN adduser -D -h /home/docker docker
RUN usermod -aG sudo docker
USER docker
ENV         USER=docker HOME=/home/docker
WORKDIR     /home/docker
RUN apt -y update
RUN apt -y install git curl nodejs python3 sudo