FROM --platform=$TARGETOS/$TARGETARCH ubuntu:18.04
LABEL org.opencontainers.image.source = &quot;https://github.com/NotTimIsReal/ptero-images&quot;
RUN adduser -D -h /home/docker docker
USER docker
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./../entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]